spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver    驱动程序是通过SPI自动注册的，手动加载驱动程序类通常是不必要的。
    url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#   是否打印出自动生产的SQL，方便调试的时候查看
    show-sql: true